
spring:
  datasource:
    name: gamble
    url: jdbc:mysql://121.196.165.230:3306/student?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=false #url
    username: root
    password: brian1223
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 配置映射文件
  type-aliases-package: team.scholarship.bean # 配置实体类
server:
  port: 821
